[package]
name = "discoserver"
version = "1.2.0"
authors = ["Benjamin Gray <bengray178@gmail.com>"]
edition = "2018"

[workspace]

[dependencies]
disco_emulator = { path = "disco_emulator" }

[dev-dependencies]
rand = "0.7.3"
