name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install ALSA
      run: |
        sudo apt-get update -yqq
        sudo apt-get install -yqq --no-install-recommends libasound2-dev
    - name: Build
      run: cargo build --verbose
#     - name: Run tests
#       run: cargo test --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: discoserver
        path: target/debug/discoserver
