name: Rust


on: push
# on: workflow_dispatch

# on:
#   push:
#     tags:
#       - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  upload-release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos, build-windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: download artifacts
        uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            discoserver/discoserver-linux.zip
            discoserver/discoserver-macos.zip
            discoserver/discoserver-windows.zip     

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install ALSA
      run: |
        sudo apt-get update -yqq
        sudo apt-get install -yqq --no-install-recommends libasound2-dev
    - name: Build
      run: cargo build --verbose --release
    - name: zip linux artifact
      run: |
        zip -r discoserver-linux target/release/discoserver
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: discoserver
        path: discoserver-linux.zip

  build-macos:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - name: zip macos artifact
      run: |
        zip -r discoserver-macos target/release/discoserver
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: discoserver
        path: discoserver-macos.zip

  build-windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - name: zip windows artifact
      run: |
        powershell Compress-Archive target\release\discoserver.exe discoserver-windows.zip 
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: discoserver
        path: discoserver-windows.zip
